project_id = "kyepsthzxzcnmbunlmvu"

[functions.import-recipes]
verify_jwt = false

[functions.get-stripe-price]
verify_jwt = false

[functions.create-checkout]
verify_jwt = true

[functions.payments-webhook]
verify_jwt = false

[functions.send-seller-message]
verify_jwt = false
